export const actionTypes = Object.freeze({
  START_GAME: 'START_GAME',
  PICTURE_OPEN: 'PICTURE_OPEN',
  PICTURES_MATCHED: 'PICTURES_MATCHED',
  PICTURE_CLOSE: 'PICTURE_CLOSE',
  VICTORY: 'VICTORY',
  RESET: 'RESET',
  SHOW_HISTORY: 'SHOW_HISTORY',
  TIME: 'TIME',
});
